# Generated by Django 5.0.6 on 2024-06-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageInactive', models.URLField()),
                ('imageActive', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageInactive', models.URLField()),
                ('imageActive', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
